files:
  - time: 1660098603236.yml
    name: 大机场 Big Airport
    url: https://bigairport.icu/api/v1/client/subscribe?token=50a0a2fec7c0413229f5a7e709f5fbb2
    selected:
      - name: GLOBAL
        now: 【直连】SIN/狮城 - 4
      - name: 大机场 Big Airport
        now: 【直连】ICN/首尔 - 80端口 - 1
    interval: 24
    subInfo:
      upload: 726637207
      download: 25261028309
      total: 1099511627776
      expire: 1716088091
    mode: rule
index: 0
