showNewVersionIcon: false
hideAfterStartup: false
randomControllerPort: false
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
systemTheme: true
