# Clash Verge Config

app_singleton_port: null
language: zh
theme_mode: system
theme_blur: false
traffic_graph: true
enable_tun_mode: null
enable_auto_launch: true
enable_silent_start: true
enable_system_proxy: false
enable_proxy_guard: false
system_proxy_bypass: null
proxy_guard_duration: 30
theme_setting: null
web_ui_list: null
clash_core: clash-meta
hotkeys: null
auto_close_connection: true
default_latency_test: ''
enable_clash_fields: true
enable_builtin_enhanced: true
proxy_layout_column: 6
