lastupdatecheck: 0
recentrepos:
- /Users/king/PycharmProjects/wuyou_outnet_spider
- /Users/king/.oh-my-zsh
- /Users/king/clone/shadowsocksr
- /Users/king/.config/jgit
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
